apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: dispatch-scaler
  namespace: robot-shop
spec:
  scaleTargetRef:
    name: dispatch
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 60
  pollingInterval: 15
  triggers:
    - type: redis
      metadata:
        address: redis.robot-shop.svc.cluster.local:6379
        listName: dispatch-jobs
        listLength: "5"
        activationListLength: "1"
        enableTLS: "false"