apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: robot-shop
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  namespaceSelector:
    matchNames:
      - robot-shop
  selector:
    matchExpressions:
      - key: service
        operator: Exists
  endpoints:
    - port: http
      path: /metrics
      interval: 15s