apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: robot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:latest
          env:
            - name: REDIS_ADDR
              value: "redis://redis.robot-shop.svc.cluster.local:6379"
          ports:
            - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: robot-shop
  labels:
    app: redis-exporter
    service: redis-exporter
spec:
  selector:
    app: redis-exporter
  ports:
    - port: 9121
      targetPort: 9121
      name: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  namespaceSelector:
    matchNames:
      - robot-shop
  selector:
    matchLabels:
      app: redis-exporter
  endpoints:
    - port: http
      interval: 15s